### ISSUE TITLE
can't build file

### ISSUE THREAD

**Issue by fm39hz** [lihaochen910/EastwardResExporter#1]
When i tried build the tool with msbuild, it throwback this troubleshooting
Build started 10/8/2021 6:03:40 PM.
     1>Project "C:\Users\Admin\Downloads\EastwardResExporter\EastwardResExporter.sln" on node 1 (default targets).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
     1>Project "C:\Users\Admin\Downloads\EastwardResExporter\EastwardResExporter.sln" (1) is building "C:\Users\Admin\D
       ownloads\EastwardResExporter\GPackTools\GPackTools.csproj" (2) on node 1 (default targets).
     2>C:\Users\Admin\Downloads\EastwardResExporter\GPackTools\GPackTools.csproj(72,5): error : ?????????????? NuGet ??
       ????"NuGet ?????"???????????????,??? http://go.microsoft.com/fwlink/?LinkID=322105??????? ..\packages\ZstdNet.1.
       4.5\build\ZstdNet.targets?
     2>Done Building Project "C:\Users\Admin\Downloads\EastwardResExporter\GPackTools\GPackTools.csproj" (default targe
       ts) -- FAILED.
     1>Done Building Project "C:\Users\Admin\Downloads\EastwardResExporter\EastwardResExporter.sln" (default targets) -
       - FAILED.

Build FAILED.

       "C:\Users\Admin\Downloads\EastwardResExporter\EastwardResExporter.sln" (default target) (1) ->
       "C:\Users\Admin\Downloads\EastwardResExporter\GPackTools\GPackTools.csproj" (default target) (2) ->
       (EnsureNuGetPackageBuildImports target) ->
         C:\Users\Admin\Downloads\EastwardResExporter\GPackTools\GPackTools.csproj(72,5): error : ?????????????? NuGet
       ??????"NuGet ?????"???????????????,??? http://go.microsoft.com/fwlink/?LinkID=322105??????? ..\packages\ZstdNet.
       1.4.5\build\ZstdNet.targets?

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.89

**Comment by lihaochen910** [comment]
I have changed the dependency library ZstdNet to ImpromptuNinjas.ZStd, download the latest one and try.

**Comment by fm39hz** [comment]
could u add the readme how to use progame?
when i try to use indexpeeker it throwback this
Unhandled Exception: System.TypeInitializationException: The type initializer for 'ZStdDCtx' threw an exception. ---> System.IO.FileNotFoundException: C:\Users\Admin\Downloads\EastwardResExporter-main\AssetIndexPeeker\bin\Debug\libzstd32.dll
You may need to specify <RuntimeIdentifier>win-x86<RuntimeIdentifier> or <RuntimeIdentifier>win<RuntimeIdentifier> in your project file.
   at ImpromptuNinjas.ZStd.Native.<>c.<.cctor>b__6_1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at ImpromptuNinjas.ZStd.Native.get_Lib()
   at ImpromptuNinjas.ZStd.Native.ZStdDCtx..cctor()
   --- End of inner exception stack trace ---
   at ImpromptuNinjas.ZStd.Native.ZStdDCtx.CreateDCtx()
   at ImpromptuNinjas.ZStd.DCtx.Create()
   at ImpromptuNinjas.ZStd.ZStdDecompressor..ctor()
   at Eastward.GPack..ctor(FileStream stream) in C:\Users\Admin\Downloads\EastwardResExporter-main\GPackTools\GPackStream.cs:line 42
   at Eastward.Program.Main(String[] args) in C:\Users\Admin\Downloads\EastwardResExporter-main\AssetIndexPeeker\Program.cs:line 33

**Comment by lihaochen910** [comment]
1.restore Nuget package
2.go "./packages/ImpromptuNinjas.ZStd/runtimes/win/native/net45", and copy 'libzstd32.dll', 'libzstd64.dll' to program dir. 
It depends on your operating system

The path might look like this:
```
/Users/Kanbaru/OneDrive/Documents/EastwardResExporter/ScriptLibraryExporter/bin/Debug/libzstd32.dll
```
on Mac
```
D:\OneDrive\Documents\EastwardResExporter\ScriptLibraryExporter\bin\Debug\libzstd32.dll
```
on Windows

**Comment by 5atu** [comment]
I did this but how do I run the program aftewards?
